### ISSUE TITLE
Set default country

### ISSUE THREAD

**Issue by cho-wtag** [angular-material-extensions/select-country#11]
I want to view an **already selected country** (using alpha2Code) from API call. Is there any solution available for now? If not is there any other way to do it?

**Comment by gchokeen** [comment]
I have same issue, I want to pre-select the country, I gave value to `country` input, It just showing the flag but not country name.

```
<mat-select-country appearance="outline" [country]="India"
                    (onCountrySelected)="onCountrySelected($event)">
                  </mat-select-country>
```
![image](https://user-images.githubusercontent.com/1717379/92074796-9365e680-edd4-11ea-8670-58afc893b2e3.png)

Any idea? how to solve it!

**Comment by christophe-mailfert** [comment]
Same problem :)

**Comment by AnthonyNahas** [comment]
which version are you using ?

**Comment by Beebeeoii** [comment]
Currently on the latest version 2.2.0. Tried setting default country by [country]="country" in .html and country="Australia" in .ts, Also tried [value] instead but also does not work. 

please assist. thanks!

**Comment by sohinim98** [comment]
I have the same error where adding `country = alpha2Code` displays the country flag, but not the country name. Please fix this ASAP. Urgent.

**Comment by AnthonyNahas** [comment]
Please when using the newest version `3.0.0` please use `[value]` instead of `[country]`

Finally, I've released a new major [version](https://www.npmjs.com/package/@angular-material-extensions/select-country) of the library `3.0.0`

With this release

<img width="726" alt="Bildschirmfoto 2020-10-23 um 22 36 45" src="https://user-images.githubusercontent.com/20149774/97051865-45719180-1580-11eb-9597-ab8c499ed5e8.png">


https://github.com/angular-material-extensions/select-country/releases/tag/3.0.0


If you love this library please share it with your team and friends and please make sure that your are not missing any 
cool angular library or component within my [angular material extensions](https://github.com/angular-material-extensions)  


thank you all and cheers 🍻

**Comment by vickieallen** [comment]
I don't think this is resolved. I am using   "@angular-material-extensions/select-country": "^3.0.4", 

If I pass the full Country object to [country] then it works, but as above, I only have the alpha2 code returned from the API and no way of populating the other fields in Country as you do not expose the full list of countries to my knowledge for me to find the country in?

Please can there be a way to set the default value from just the alpha2 code. Currently it simply sets the flag, but leaves the text blank which is not ideal.

**Comment by AnthonyNahas** [comment]
@vickieallen I would appreciate a PR from you to improve that 🍻

**Comment by vickieallen** [comment]
@AnthonyNahas  as requested 👍 would be good to get this asap as need this fix for a client hoping to launch in the next week or so.

**Comment by AnthonyNahas** [comment]
PR merged

release maybe tonight 

thank you

**Comment by AnthonyNahas** [comment]
@vickieallen [4.0.3](https://www.npmjs.com/package/@angular-material-extensions/select-country) is now live

thank you all once again

**Comment by prayatna** [comment]
after using "@angular-material-extensions/select-country": "^4.0.3" I have started getting `Cannot read property 'find' of undefined` where the undefined is `this.countries` `line 90` of `mat-select-country.component.ts`.

**Comment by Santisosa404** [comment]
Can be the version 4.0.3 used on Angular 11.2.14 or only 11.0.0? Thank you!
