### ISSUE TITLE
predefined [countries] input not working

### ISSUE THREAD

**Issue by SnappingTurtle** [angular-material-extensions/select-country#42]
I rolled back to version 1.0.1 so that I could overcome the bug where default input label does not show on first render, but now, I am trying to input a predefined countries list (to overcome terrible performance) and it does not recognize the countries list input.

**To Reproduce**
Add a select-country component to your layout.
configure with [countries]="predefinedCountries" to show a subset of countries.
configure a list in your controller predefinedCountries: Country[] = {...} with a short list.

**Expected behavior**
I would expect the control to show the short list of predefined countries.
However, the entire list (slow loading) of countries is still present.

**Screenshots**

**Additional context**
Is this input supported in version 1.0.1 or was it added in later versions?

**Comment by AnthonyNahas** [comment]
@KingDarBoja  you have right! Please when using the newest version `3.0.0` please use `[value]` instead of `[country]`

Finally, I've released a new major [version](https://www.npmjs.com/package/@angular-material-extensions/select-country) of the library `3.0.0`

With this release

<img width="726" alt="Bildschirmfoto 2020-10-23 um 22 36 45" src="https://user-images.githubusercontent.com/20149774/97051865-45719180-1580-11eb-9597-ab8c499ed5e8.png">


https://github.com/angular-material-extensions/select-country/releases/tag/3.0.0


If you love this library please share it with your team and friends and please make sure that your are not missing any 
cool angular library or component within my [angular material extensions](https://github.com/angular-material-extensions)  


thank you all and cheers 🍻
