### ISSUE TITLE
When rendering a default country (using alpha2Code), the flag shows up, but the country name doesn't. Is there any other way to achieve the same goal?

### ISSUE THREAD

**Issue by sohinim98** [angular-material-extensions/select-country#46]
**Describe the bug**
When rendering a default country (using alpha2Code), the flag shows up, but the country name doesn't. Is there any other way to achieve the same goal?

**To Reproduce**
My code-
```
<mat-select-country
              appearance="outline"
              class="billing-field--dropdown"
              label="Country"
              country="{{subscription?.autofill ? autofill.billing_address.country : ''}}"
              [itemsLoadSize]="5"
              (onCountrySelected)="onCountrySelected($event)"
            >
</mat-select-country>
```
**Expected behavior**
When setting the default value using `country=alpha2Code`, both the country name and the country flag should show up.

**Screenshots**
<img width="399" alt="Screen Shot 2020-10-22 at 1 19 58 PM" src="https://user-images.githubusercontent.com/35234448/96907516-4f54a100-1469-11eb-9ef1-b8274a2a0870.png">

**Desktop (please complete the following information):**
- Any browser/device

**Smartphone (please complete the following information):**
- Any device

**Comment by KingDarBoja** [comment]
It should be `[value]="defaultValue"` instead of `[country]="defaultValue"`.

**Comment by soujini** [comment]
> It should be `[value]="defaultValue"` instead of `[country]="defaultValue"`.

I have the same issue and did try with the value field, but no luck. I also noticed that the country name does not show up but on click of the input control, it shows up.

**Comment by sohinim98** [comment]
@KingDarBoja According to the documentation (https://angular-material-extensions.github.io/select-country/doc/index.html), the `country` attribute needs to be set to a string (possible values are Country interface properties, case-insensitive) - in my case that's the alpha2Code. The value object accepts the entire object, not the string, and that doesn't seem to work either. It's an issue on their end that they need to fix.

**Comment by KingDarBoja** [comment]
I am pretty sure the documentation is outdated as you can see at my pull request #43 as I also tested it locally while doing those changes. The `value` change was introduced at this commit: https://github.com/angular-material-extensions/select-country/commit/7ad05b5a8e4d1c5a7c2a4172cab9a014ef247456 hence my previous comment.

**Comment by AnthonyNahas** [comment]
@KingDarBoja  you have right! Please when using the newest version `3.0.0` please use `[value]` instead of `[country]`

Finally, I've released a new major [version](https://www.npmjs.com/package/@angular-material-extensions/select-country) of the library `3.0.0`

With this release

<img width="726" alt="Bildschirmfoto 2020-10-23 um 22 36 45" src="https://user-images.githubusercontent.com/20149774/97051865-45719180-1580-11eb-9597-ab8c499ed5e8.png">


https://github.com/angular-material-extensions/select-country/releases/tag/3.0.0


If you love this library please share it with your team and friends and please make sure that your are not missing any 
cool angular library or component within my [angular material extensions](https://github.com/angular-material-extensions)  


thank you all and cheers 🍻
