### ISSUE TITLE
[showCallingCode] binding is not working

### ISSUE THREAD

**Issue by elonaire** [angular-material-extensions/select-country#81]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rogermax** [comment]
In the commit "example demo showCallingCode" of the PR #80 I made a demo changing the [showCallingCode] binding and it's working. Maybe you are passing a string instead of a boolean?

If you're using a mat-select for example the value returned by the select is a string not a boolean. So it could be done this way:

TS
```javascript
  showCallingCode = 'false';
```

HTML
```html
        <div>
            <mat-form-field appearance="fill">
                <mat-label>Choose showCallingCode</mat-label>
                <mat-select [(value)]="showCallingCode">
                    <mat-option value="true">true</mat-option>
                    <mat-option value="false">false</mat-option>
                </mat-select>
            </mat-form-field>
        </div>
        <mat-select-country appearance="outline"
                            label="Country"
                            [language]="languageSelected"
                            [autocomplete]="'no'"
                            [showCallingCode]="showCallingCode == 'true'"
                            (onCountrySelected)="onCountrySelected($event)">
        </mat-select-country>
```

**Comment by AnthonyNahas** [comment]
#80 is already merged
